---
server.port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/omprsingh/BookReviewAppConfigStore.git"
          clone-on-start: true
          username: "omprsingh"
          password: "AumGitHub@32$"
eureka:
  client:
    region: "default"
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"
    healthcheck:
      enabled: true